[[redirects]]
  from = "/apply"
  to = "https://forms.gle/i68cT5S3mhcQiXbq7"


[[redirects]]
  from = "/rsvp"
  to = "https://forms.gle/StXKhkycSh78iqNS8"



[[redirects]]
  from = "/submit"
  to = "https://forms.gle/sQLdn4MYYDq9F2Jw7"


[[redirects]]
  from = "/post/bot-free-speech"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
