[[redirects]]
  from = "/apply"
  to = "https://docs.google.com/forms/d/11YtXsa1IGrZpFNq3aFNUMPivyBCzqrArihGK_W5EuKk/edit?usp=sharing"

  
[[redirects]]
  from = "/rsvp"
  to = "https://docs.google.com/forms/d/1hwe2oc95-vYFa93a-s4YSIy52cDDesLpl4bR_04PGlM/edit?usp=sharing"
