[[redirects]]
  from = "/apply"
  to = "https://forms.gle/Z7Kfq3p8jGKer5Ea7"


[[redirects]]
  from = "/rsvp"
  to = "https://forms.gle/StXKhkycSh78iqNS8"



[[redirects]]
  from = "/submit"
  to = "https://forms.gle/sQLdn4MYYDq9F2Jw7"
